version: '3.7'

services:

  alluxio-master:
    image: 'alluxio/alluxio-enterprise:latest'
    hostname: alluxio-master
    container_name: alluxio-master
    networks:
      custom:
        ipv4_address: 172.23.0.2
    depends_on:
      - minio-create-buckets
    extra_hosts:
      - "alluxio-master:172.23.0.2"
      - "alluxio-worker:172.23.0.3"
      - "minio         :172.23.0.7"
    environment:
      # Run the command outside of this file to get the base64 formated license file
      # Like this: export ALLUXIO_LICENSE_BASE64=$(cat ./my-alluxio-license-file.json | base64)
      ALLUXIO_LICENSE_BASE64: ${ALLUXIO_LICENSE_BASE64}
      ALLUXIO_JAVA_OPTS: "-Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage -Dalluxio.master.hostname=localhost"
    volumes:
      - alluxio-data:/opt/alluxio/underFSStorage
      - ./alluxio-files/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties:ro
    expose:
      - "19998"
      - "19999"
      - "19200"
    ports:
      - "19998:19998"
      - "19999:19999"
    command: ["master"]

  alluxio-worker:
    image: 'alluxio/alluxio-enterprise:latest'
    hostname: alluxio-worker1
    container_name: alluxio-worker1
    networks:
      custom:
        ipv4_address: 172.23.0.3
    extra_hosts:
      - "alluxio-master:172.23.0.2"
      - "alluxio-worker:172.23.0.3"
      - "minio         :172.23.0.7"
    shm_size: '1gb'
    depends_on:
      - alluxio-master
    environment:
      ALLUXIO_JAVA_OPTS: "-Dalluxio.master.hostname=alluxio-master -Dalluxio.worker.ramdisk.size=1G -Dalluxio.master.mount.table.root.ufs=/opt/alluxio/underFSStorage -Dalluxio.worker.hostname=alluxio-worker"
    volumes:
      - alluxio-data:/opt/alluxio/underFSStorage
      - ./alluxio-files/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties:ro
    expose:
      - "29999"
      - "30000"
      - "30001"
      - "30003"
      - "39999"
    ports:
      - "29999:29999"
      - "30000:30000"
      - "39999:39999"
    command: ["worker"]

  alluxio-mount-minio-bucket:
    image: 'alluxio/alluxio-enterprise:latest'
    container_name: alluxio-mount-minio-bucket
    networks:
      custom:
        ipv4_address: 172.23.0.11
    extra_hosts:
      - "alluxio-master:172.23.0.2"
      - "alluxio-worker:172.23.0.3"
    depends_on:
      - alluxio-master
      - minio-create-buckets
    environment:
      ALLUXIO_JAVA_OPTS: "-Dalluxio.master.hostname=alluxio-master"
    volumes:
      - ./alluxio-files/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties:ro
    entrypoint: >
      /bin/sh -c "
        sleep 5
        alluxio fs mount \
           --option alluxio.underfs.s3.endpoint=http://minio:9000 \
           --option alluxio.underfs.s3.disable.dns.buckets=true \
           --option alluxio.underfs.s3.inherit.acl=false \
           --option s3a.accessKeyId=minio \
           --option s3a.secretKey=minio123 \
           /hive s3a://hive/
        sleep 5
        alluxio fs loadMetadata /hive
        alluxio fs chmod -R 777 /
        alluxio fs chmod -R 777 /hive/
        alluxio fs chmod -R 777 /hive/warehouse
        exit 0
        "
  mariadb:
    image: 'mariadb:latest'
    hostname: mariadb
    container_name: mariadb
    networks:
      custom:
        ipv4_address: 172.23.0.4
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    volumes:
      - mariadb-data:/var/lib/mysql

  trino-coordinator:
    image: 'trinodb/trino:385'
    hostname: trino-coordinator
    container_name: trino-coordinator
    networks:
      custom:
        ipv4_address: 172.23.0.5
    extra_hosts:
      - "alluxio-master:172.23.0.2"
      - "alluxio-worker:172.23.0.3"
      - "mariadb       :172.23.0.4"
      - "minio         :172.23.0.7"
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/tmp/etc-trino
      - ./alluxio-files:/tmp/alluxio-files
      - ./conf:/tmp/conf
    command:
      - /bin/bash
      - -c 
      - |
        find /usr/lib/trino -name alluxio*shaded* -exec rm {} \;
        cp /tmp/alluxio-files/alluxio-enterprise-*-client.jar /usr/lib/trino/plugin/hive/
        cp -R /tmp/etc-trino/* /etc/trino/
        cp /tmp/alluxio-files/alluxio-core-site.xml /etc/trino/core-site.xml
        /usr/lib/trino/bin/run-trino

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: hive-metastore
    container_name: hive-metastore
    networks:
      custom:
        ipv4_address: 172.23.0.6
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
      - ./alluxio-files:/tmp/alluxio-files
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
      - minio
      - alluxio-mount-minio-bucket
    entrypoint: >
      /bin/sh -c "
        cp /tmp/alluxio-files/alluxio-enterprise-*-client.jar /opt/apache-hive-metastore-3.0.0-bin/lib/
        echo '#### Hive /opt/apache-hive-metastore-3.0.0-bin/lib/ ###'
        ls -al /opt/apache-hive-metastore-3.0.0-bin/lib/ | grep alluxio
        /entrypoint.sh
        "

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    networks:
      custom:
        ipv4_address: 172.23.0.7
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  minio-create-buckets:
    image: minio/mc:latest
    container_name: minio-create-buckets
    networks:
      custom:
        ipv4_address: 172.23.0.10
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      if [ \"`/usr/bin/mc ls myminio`\" == \"\" ]; then 
         echo \"Creating bucket myminio/hive\" && \
         /usr/bin/mc mb myminio/hive && \
         /usr/bin/mc policy download myminio/hive && \
         /usr/bin/mc cp /etc/motd myminio/hive/warehouse/.temp_file; 
      else 
         echo \"Bucket myminio/hive already exists, skipping create\"; 
      fi;
      exit 0
      "

  spark-master:
    image: docker.io/bitnami/spark:3.3
    hostname: spark-master
    container_name: spark-master
    networks:
      custom:
        ipv4_address: 172.23.0.8
    extra_hosts:
      - "alluxio-master:172.23.0.2"
      - "alluxio-worker:172.23.0.3"
      - "hive-metastore:172.23.0.6"
      - "spark-master:  172.23.0.8"
      - "spark-worker:  172.23.0.9"
    volumes:
      - ./alluxio-files:/tmp/alluxio-files
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8081:8080'
    command:
      - /bin/sh
      - -c 
      - |
        cp /tmp/alluxio-files/alluxio-enterprise-*-client.jar /opt/bitnami/spark/jars/
        echo "spark.hadoop.hive.metastore.uris=thrift://hive-metastore:9083" >> /opt/bitnami/spark/conf/spark-defaults.conf
        cp /tmp/alluxio-files/alluxio-core-site.xml /opt/bitnami/spark/conf/core-site.xml
        /opt/bitnami/scripts/spark/run.sh

  spark-worker:
    image: docker.io/bitnami/spark:3.3
    hostname: spark-worker
    container_name: spark-worker
    networks:
      custom:
        ipv4_address: 172.23.0.9
    extra_hosts:
      - "alluxio-master:172.23.0.2"
      - "alluxio-worker:172.23.0.3"
      - "spark-master:  172.23.0.8"
      - "spark-worker:  172.23.0.9"
    volumes:
      - ./alluxio-files:/tmp/alluxio-files
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command:
      - /bin/sh
      - -c 
      - |
        cp /tmp/alluxio-files/alluxio-enterprise-*-client.jar /opt/bitnami/spark/jars/
        echo "spark.hadoop.hive.metastore.uris=thrift://hive-metastore:9083" >> /opt/bitnami/spark/conf/spark-defaults.conf
        cp /tmp/alluxio-files/alluxio-core-site.xml /opt/bitnami/spark/conf/core-site.xml
        /opt/bitnami/scripts/spark/run.sh
    ports:
      - '8082:8081'
    
volumes:
  mariadb-data:
    driver: local
  minio-data:
    driver: local
  alluxio-data:
    driver: local

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.23.0.0/16
        gateway: 172.23.0.1
